apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certificate
  template:
    metadata:
      labels:
        app: certificate
    spec:
      containers:
        - name: certificate
          image: udemyclone/certificate
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "certificate-db-srv"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "udemy-certificate_service_dev"
            - name: REDIS_HOST
              value: "redis-srv"
            - name: REDIS_PORT
              value: "6379"
            - name: NODE_ENV
              value: "development"
            - name: JWT_EXPIRE
              value: "36000s"
            - name: NATS_URL
              value: "nats://nats-srv:4222"
          envFrom:
            - secretRef:
                name: user-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: certificate-srv
spec:
  selector:
    app: certificate
  ports:
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005