apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - udemyclone.dev
      secretName: udemyclone-tls
  rules:
    - host: udemyclone.dev
      http:
        paths:
          # user-service routes
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user-srv
                port:
                  number: 3001

          # auth-service routes
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3002

          # category-service routes
          - path: /category
            pathType: Prefix
            backend:
              service:
                name: category-srv
                port:
                  number: 3003

          # course-service routes
          - path: /course
            pathType: Prefix
            backend:
              service:
                name: course-srv
                port:
                  number: 3004

          # certificate-service routes
          - path: /certificate
            pathType: Prefix
            backend:
              service:
                name: certificate-srv
                port:
                  number: 3005