apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interaction
  template:
    metadata:
      labels:
        app: interaction
    spec:
      containers:
        - name: interaction
          image: udemyclone/interaction
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "interaction-db-srv"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "udemy-interaction_service_dev"
            - name: NODE_ENV
              value: "development"
            - name: JWT_EXPIRE
              value: "36000s"
            - name: NATS_URL
              value: "nats://nats-srv:4222"
          envFrom:
            - secretRef:
                name: user-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: interaction-srv
spec:
  selector:
    app: interaction
  ports:
    - name: http
      protocol: TCP
      port: 3006
      targetPort: 3006